INSERT INTO recipes (recipe_name, recipe_img, total_calories, instructions)
VALUES ('Chipotle Black Bean Dip', 'cbbdip.jpg', 100, "In a food processor, combine the beans, chipotles, lime juice, and water. Blend until fairly smooth, about 1 minute. 
There should still be a bit of texture to the beans. -Prep Time: 15 Minutes"),
('Chicken Fajitas', 'chickFaj.jpg', 299, "1. In a large bowl, combine the chicken, onion, bell peppers, chili powder, garlic powder, cumin, cornstarch, and chicken stock.
Toss to coat well. 2.Heat the olive oil in a large pot over high heat. When it starts to smoke, add the chicken and vegetable mixture and stir vigorously until 
the vegetables soften and the chicken is cooked through, about 5 minutes. Remove from the heat and let stand for 5 minutes to allow the sauce to thicken. 
3. Warm the tortillas by wrapping them in a damp towel and placing in the microwave for 30 seconds. 4. Divide the chicken mixture among the 8 tortillas and fold over. 
-Prep time: 10 Minutes -Cook time: 10 minutes"),
('Creamy Pesto Cucumber', 'cucNoodle.jpg', 139, "1. Place the cashews in a small container and add enough water just to cover. Transfer to the refrigerator 
to soak overnight. 2. Reserving the soaking water, drain the cashews and transfer to a blender. Add the basil, olive oil, lemon juice, and garlic and puree 
until the mixture acheives the texture of ricotta. If the mixture is dry,add some of the soaking liquid 1 tablespoon at a time until it comes together. 
Season the pesto with salt and pepper and set aside. 3. Using a mandoline with a 1/8-inch tooth attachment, shave the cucumbers into thin noodles. Place 
in a large bowl and pour the pesto over the top. Mix well. -Prep time: 20 Minutes -Soak time: overnight"),
('String Bean Salad', 'sbSalad.jpg', 79, "1. Bring a large pot of water to a boil. 2. Add some salt to the water and boil the beans until tender, about 7 minutes. 
Drain the beans and let cool. 3. In a large bowl, combine the beans, tomatoes, chives, vinegar, and olive oil. Season with salt and toss well to coat. 
-Prep time: 15 Minutes -Cook time: 7 Minutes"),
('Avocado Crema Salad', 'avCrema.jpg', 132, "1. In a large bowl, combine the napa cabbage, jicama, cucumber, and cilantro. Set aside. 2. mash 
the avocado with a fork until mostly smooth. Switch to a whisk and add the yogurt and lime juice. 3. Dress the cabbage mixture and transfer to serving bowls. 
Top with the cherry tomatoes. -Prep time: 20 minutes"),
('Chicken Chorizo Soup', 'chChorSoup.jpg', 166, "1. Heat the olive oil in a large pot over medium heat. Add the onions and bell pepper and sweat until soft and translucent, 
about 10 minutes. 2. Add the ancho powder and cumin and continue cooking for 1 to 2 minutes, until fragrant. 3. Add the chorizo, chicken stock, and black beans 
and bring to a boil. Cook until the beans begin to break down and thicken the soup, about 5 minutes. Season with salt and pepper. Transfer to bowls and top 
with the cilantro. -Prep time: 10 minutes -Cook time: 15 minutes"),
('Coconut Chicken Soup', 'chickCoco.jpg', 275, "1. Heat the oil in a large pot over medium heat. Add the onion and celery and sweat until soft and translucent, 
about 10 minutes. 2. Increase the heat to high, add the chicken, and cook until browned on all sides, about 5 minutes. 3. Add the coconut milk, chicken stock, 
and lime zest and bring to a boil. Cook until the chicken is tender and cooked through, about 10 minutes. 4. Season with salt and pepper and serve garnished 
with the cilantro. -Prep time: 10 Minutes -Cook time: 20 Minutes"),
('Sweet Pea Hummus', 'peaHummus.jpg', 97, "In a food processor, combine the peas, tahini, olive oil, garlic, lemon juice, and water and pulse 5 times to get the mixture 
going. Then puree until smooth, about 1 minute. Use immediately or store tightly sealed in the refrigerator for up to 1 week. -Prep Time: 5 Minutes"),
('Pork And Pepper Sauce', 'pChops.jpg', 181, "1. Heat the olive oil in a large saute pan over high heat. Add the pork chops and brown for about 3 minutes on each 
side. Transfer to a baking sheet to rest. 2. In a bowl, stir the cornstarch into the pork broth. 3. Drain the oil from the saute pan and return to medium heat. 
Deglaze the pan with the stock and whisk until the stock boils and thickens. Season with the pepper. -Prep time: 5 Minutes -Cook time: 15 Minutes"),
('Asparagus Salad', 'aspTomato.jpg', 50, "1. Heat the olive oil in a large saute pan over high heat. When the oil just begins to smoke, add the asparagus and 
rosemary and cook, stirring frequently, until softened, about 5 minutes. 2. Transfer the asparagus to a large bowl and add the tomatoes and vinegar. Season 
with salt and pepper and serve. -Prep time: 10 Minutes -Cook time: 5 Minutes"),
('English Pea Frittata', 'frittata.jpg', 96, "1. Preheat the oven to 325 F. 2. Heat a 6-inch nonstick ovenproof skillet over medium heat. Add the 
red onion and sweat until soft, about 7 minutes. Add the peas and cook for 3 minutes. Add the turmeric and eggs and stir with a silicone spatula until about 
half-set. 3. Move the pan to the oven and bake until the eggs are cooked, 7 to 10 minutes. -Prep time: 5 Minutes -Cook time: 15 Minutes"),
('Sirloin And Asparagus', 'aspSirloin.jpg', 290, "1. Preheat the oven to 400 F. 2. Heat the grapeseed oil in a large saute pan over high heat until very hot. 
Add the sirloin, garlic, and thyme and cook until one side is browned and releases from the pan readily, about 3 minutes. Flip and cook another 3 minutes. 
Discard the garlic, transfer to a baking sheet, and move to the oven to finish, about 5 minutes for medium-rare. 3. In the pan used to brown the steak, add 
the asparagus, vinegar, and water. Cook over high heat until the asparagus is softened and browned, about 5 minutes. 4. remove the steak from the oven, and 
allow to rest for 10 minutes before slicing. Serve with the asparagus. -Prep time: 10 Minutes -Cook time: 15 Minutes"),
('Easy Fish Bowls', 'fishBowl.jpg', 556, "1. Cook your rice either via a rice-cooker or a small pot of water on the stove. If using a pot, cover your rice with a cup of water 
and bring to a boil. Then turn the heat to low, and simmer until all the water has gone, being careful to not burn the bottom of the rice. Remove the rice from 
the heat and let it cool. 2. Fry up your salmon (any choice of fish works here - whiting, mahi mahi, etc. This is a chance to finally use that frozen fish that's 
been lurking in the back of the freezer) in a nonstick pan with a pat of butter, salt, and pepper to taste. When the fish is cooked to your liking, remove it 
from the heat and allow to rest. 3. Scoop all the rice into your favorite salad bowl, top with all the condiments and veggies, then place the fish on top. 
-Prep time: 5 Minutes -Cook time: 20 Minutes"),
('Celebrity Breakfast', 'egg.jpg', 386, "This recipe is eaten by a certain famous movie star... and probably all her friends. Hence the name. Mash the avocado with a fork to 
make it creamy, or cut in thin slices and layer them on the toasted slices of bread. If you've chosen to mash, add in the salt and pepper, else sprinkle the salt and 
pepper over the slices. Then sprinkle any savory herbs you prefer. Cilantro, dill, lemon juice, and italian seasoning are all excellent options. Just a pinch. 
Then, poach your eggs in boiling water for 3 minutes and place those eggs atop the avocado layer. Voila! You have a powerful breakfast that's easy to make, delicious 
to eat, and super healthy for you. As alternative options, you can fry your eggs, use a different kind of grain bread, use more avocado, and garnish with heirloom 
tomatoes. The sky's the limit, and this is your breakfast. Make it what you want."),
('Chicken Ranch Casserole', 'casserole.jpg', 469, "1. Preheat the oven to 375 F. 2. Instead of broccoli, you could use a pound of frozen spinach, thawed and drained. 
Otherwise, place the broccoli into a pot of water and bring to a boil. Simmer for 1-2 minutes until bright green. 3. Combine the chicken, bacon, broccoli, 
garlic, ranch dressing, and half of the shredded cheeses in a large bowl. Stir until well incorporated. Transfer to a 9x13 inch glass or stoneware casserole 
dish. 4. Top with the remaining shredded mozzarella and cheddar cheeses. 5. Bake for about 15 minutes until hot and bubbly. -Prep time: 5 Minutes -Cook time: 
15 Minutes");

INSERT INTO ingredients (ingredient_name) 
VALUES ('black beans, drained and rinsed'),
('chipotle peppers in adobo sauce'),
('limes, juiced'),
('boneless, skinless chicken breast, cut into 1/2-inch wide strips'),
('onion, sliced'),
('bell peppers, cut into strips'),
('chili powder'),
('garlic powder'),
('ground cumin'),
('corn tortillas'),
('raw cashews'),
('basil leaves'),
('English cucumbers'),
('string beans, trimmed'),
('chopped chives'),
('red wine vinegar'),
('napa cabbage, chopped'),
('jicama, chopped'),
('cucumber, chopped'),
('unsweetened non-dairy coconut yogurt'),
('lime juice'),
('red bell pepper'),
('ancho chile powder'),
('cumin'),
('chicken chorizo, cut into 1/2-inch-thick half moons'),
('coconut oil'),
('onion, diced'),
('celery, diced'),
('boneless, skinless chicken breast, cut into bite-sized chunks'),
('lite coconut milk'),
('chicken stock'),
('limes, zested'),
('cilantro'),
('tahini'),
('lemon juice'),
('lean pork chops'), 
('cornstarch'),
('pork or beef broth'),
('olive oil'),
('asparagus'),
('rosemary leaves'),
('halved cherry tomatoes'),
('champagne vinegar'),
('salt'),
('pepper'),
('red onion, sliced'),
('frozen peas, thawed'),
('finely grated fresh turmeric'),
('eggs, beaten'),
('grapeseed oil'),
('beef sirloin'),
('garlic, crushed'),
('thyme leaves'),
('water'),
('salmon'),
('unagi sauce'),
('mayonnaise, any variety'),
('soy sauce'),
('sriracha, optional'),
('wasabi, optional'),
('white, short-grain rice'),
('green onion'),
('grated carrot'),
('dried seaweed'),
('avocado'),
('eggs'),
('rye bread, toasted'),
('herbs to taste'),
('chicken breast, cooked and shredded'),
('bacon, cooked and chopped'),
('garlic'),
('Ranch dressing'),
('mozzarella cheese'),
('cheddar cheese'),
('broccoli, chopped'),
('almond flour');

INSERT INTO recipe_details (recipe_id, ingredient_id, quantity, metric)
VALUES (1, 1, 2, 'cups canned'),
(1, 2, 3, 'regular'),
(1, 3, 2, 'regular'),
(1, 54, 2, 'Tablespoons'),
(2, 4, 1, 'pound'),
(2, 5, 1, 'large'),
(2, 6, 2, 'green'),
(2, 7, 2, 'teaspoons'),
(2, 8, 1.5, 'teaspoons'),
(2, 9, 3/4, 'teaspoon'),
(2, 37, 1, 'Tablespoon'),
(2, 31, 1/4, 'cup'),
(2, 39, 1, 'Tablespoon'),
(2, 10, 8, 'toasted'),
(3, 11, 1/4, 'cup'),
(3, 12, 1, 'packed cup'),
(3, 39, 1, 'Tablespoon'),
(3, 35, 2, 'Tablespoons'),
(3, 71, 1, 'clove'),
(3, 44, 1, 'desired pinch'),
(3, 45, 1, 'desired pinch'),
(3, 13, 2, 'seedless'),
(4, 44, 1, 'dash of'),
(4, 14, 1, 'pound'),
(4, 42, 2, 'cups'),
(4, 15, 1/2, 'cup'),
(4, 16, 2, 'Tablespoons'),
(4, 39, 1, 'Tablespoon'),
(5, 17, 5, 'cups'),
(5, 18, 2.5, 'cups'),
(5, 19, 1, 'large'),
(5, 33, 1/2, 'cup chopped'),
(5, 65, 1, 'large'),
(5, 20, 1/2, 'cup'),
(5, 21, 2, 'Tablespoons'),
(5, 42, 1, 'cup'),
(6, 39, 1, 'Tablespoon'),
(6, 27, 1, 'cup'),
(6, 22, 1/2, 'cup diced'),
(6, 23, 1, 'teaspoon'),
(6, 24, 1/2, 'teaspoon'),
(6, 25, 2, 'links fully cooked'),
(6, 31, 4, 'cups reduced-sodium'),
(6, 1, 1, 'can (15 ounce)'),
(6, 44, 1, 'dash to taste'),
(6, 45, 1, 'dash to taste'),
(6, 33, 1/2, 'cup leafy'),
(7, 26, 1, 'Tablespoon'),
(7, 27, 2, 'cups'),
(7, 28, 1.5, 'cups'),
(7, 29, 1, 'pound'),
(7, 30, 1.5, 'cups'),
(7, 31, 4, 'cups'),
(7, 32, 2, 'regular'),
(7, 44, 1, 'dash to taste of'),
(7, 45, 1, 'dash to taste of'),
(7, 33, 1.5, 'cups leafy'),
(8, 47, 1, 'cup'),
(8, 34, 2, 'Tablespoons'),
(8, 39, 1, 'Tablespoon'),
(8, 71, 1, 'clove'),
(8, 35, 2, 'Tablespoons'),
(8, 54, 2, 'Tablespoons'),
(9, 39, 1, 'Tablespoon'),
(9, 36, 1, 'pound (at least 4)'),
(9, 37, 4, 'teaspoons'),
(9, 38, 14, 'ounces reduced-sodium'),
(9, 45, 1/2, 'teaspoon black'),
(10, 39, 1, 'Tablespoon'),
(10, 40, 1, 'bunch'),
(10, 41, 1/2, 'sprig'),
(10, 42, 2, 'cups'),
(10, 43, 1, 'Tablespoon'),
(10, 44, 1, 'desired dash of'),
(10, 45, 1, 'desired dash of'),
(11, 46, 1, 'cup'),
(11, 47, 1/2, 'cup'),
(11, 48, 1, 'Tablespoon'),
(11, 49, 4, 'large'),
(12, 50, 1, 'Tablespoon'),
(12, 51, 1, 'pound'),
(12, 52, 2, 'cloves'),
(12, 53, 1.5, 'Tablespoons'),
(12, 40, 2, 'bunches trimmed'),
(12, 43, 2, 'Tablespoons'),
(12, 54, 1/4, 'cup'),
(13, 55, 4, 'ounces'),
(13, 56, 2, 'Tablespoons'),
(13, 57, 3, 'Tablespoons'),
(13, 58, 2, 'Tablespoons'),
(13, 59, 1, 'teaspoon'),
(13, 60, 1, 'teaspoon'),
(13, 61, 1/2, 'cup'),
(13, 62, 1/4, 'stalk'),
(13, 63, 1/4, 'cup'),
(13, 64, 1/4, 'cup chopped'),
(13, 65, 1/4, 'large'), 
(14, 66, 2, 'medium to large'),
(14, 67, 2, 'slices'),
(14, 65, 1/3, 'large'),
(14, 44, 1, 'dash'), 
(14, 45, 1, 'dash'),
(14, 68, 1, 'dash'),
(15, 69, 2, 'pounds'),
(15, 70, 8, 'slices'),
(15, 71, 3, 'cloves'), 
(15, 72, 3/4, 'cup'),
(15, 73, 1, 'cup'),
(15, 74, 1, 'cup'),
(15, 75, 4, 'cups'); 